name: capsplit
description: Personal Finance App with wallet-based money segregation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase for backend
  supabase_flutter: ^2.0.2
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # UI/UX
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  
  # Utilities
  intl: ^0.18.1
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  uuid: ^4.2.1
  
  #splash_screen
  lottie: ^2.7.0
  flutter_svg: ^2.0.7
  # 3D Visualization (we'll add later)
  # flutter_3d_controller: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/